apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: eldenring
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name:  POSTGRES_USER
              value: eldenring
            - name:  POSTGRES_DB
              value: eldenring_todo
            - name:  POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eldenring-secrets
                  key:  POSTGRES_PASSWORD
          volumeMounts:
            - name:      pg-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "eldenring"]
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: eldenring
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432