"""init

Revision ID: 198bf65f2ca7
Revises: 
Create Date: 2026-05-03 14:32:39.613193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198bf65f2ca7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sessions_user_date'))

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_todos_session'))
        batch_op.drop_index(batch_op.f('idx_todos_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_todos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_todos_session'), ['session_id'], unique=False)

    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sessions_user_date'), ['user_id', 'session_date'], unique=False)

    # ### end Alembic commands ###
